// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE7p2OMnU7cMNCcH9AwAaKuEN-0h4NYNU',
    appId: '1:824344128733:web:25b821d867e87885c73f34',
    messagingSenderId: '824344128733',
    projectId: 'super-cool-project-9c548',
    authDomain: 'super-cool-project-9c548.firebaseapp.com',
    databaseURL: 'https://super-cool-project-9c548-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'super-cool-project-9c548.firebasestorage.app',
    measurementId: 'G-DWXGNZQWXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26ArSjff823zOFthzDvZAcFaWyzS8YBw',
    appId: '1:824344128733:android:d25bfb9783446755c73f34',
    messagingSenderId: '824344128733',
    projectId: 'super-cool-project-9c548',
    databaseURL: 'https://super-cool-project-9c548-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'super-cool-project-9c548.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE7p2OMnU7cMNCcH9AwAaKuEN-0h4NYNU',
    appId: '1:824344128733:web:37a7735207b1ecb7c73f34',
    messagingSenderId: '824344128733',
    projectId: 'super-cool-project-9c548',
    authDomain: 'super-cool-project-9c548.firebaseapp.com',
    databaseURL: 'https://super-cool-project-9c548-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'super-cool-project-9c548.firebasestorage.app',
    measurementId: 'G-0ZFNS7925E',
  );

}